---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Website:
    - sasrblx.co.uk:
        href: https://sasrblx.co.uk
        description: Home website.

- Content Delivery Network:
    - Zipline:
        href: https://cdn.sasrblx.co.uk
        description: Website for Content Delivering.

    - Zipline Status:
        href: https://status.cdn.sasrblx.co.uk
        description: Monitor Content Delivery Network uptime.


- Content Delivery Network:
    - Portainer:
        href: https://portainer.sasrblx.co.uk
        description: Website for Monitoring Containers.

    - Portainer Status:
        href: https://status.portainer.sasrblx.co.uk
        description: Monitor Portainer uptime.
