---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Website:
    - sasrblx.co.uk:
        href: https://sasrblx.co.uk
        description: Home website.

- Content Delivery Network:
    - Zipline:
        href: https://cdn.sasrblx.co.uk/
        description: Content Delivery Network service.
    - Zipline Status:
        href: https://status.cdn.sasrblx.co.uk/
        description: Content Delivery Network uptime.

- Portainer:
    - Portainer:
        href: https://portainer.sasrblx.co.uk/
        description: Portainer uptime.
