---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Dashboard

background: https://cdn.discordapp.com/attachments/797099286470852629/1296248349040574464/homepage_background.png?ex=671198d9&is=67104759&hm=a2734dda58e6b0b47f7d12896469f5fa5fd8c9bdaeafd25b90af51f412eb9f0b&

theme: light

language: en

hideVersion: true

headerStyle: clean

providers:
  weatherapi: 28583918d15d46c18ba231725241610
